import { Spot } from '../types/spot'

export const MOCK_SPOTS: Spot[] = [
  {
    id: '1',
    name: 'DUMBO Waterfront',
    description: 'Iconic Brooklyn Bridge framed through the Manhattan Bridge arches. Best at golden hour when the warm light hits the bridge cables.',
    latitude: 40.7033,
    longitude: -73.9903,
    founder_id: 'user-1',
    rank: 'popular',
    difficulty: 'easy',
    tags: ['sunset', 'cityscape', 'architecture'],
    cover_photo_url: '',
    photo_count: 312,
    navigation_count: 189,
    best_time_start: '18:30',
    best_time_end: '20:00',
    gear_recommendation: '24-70mm f/2.8',
    created_at: '2024-03-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Griffith Observatory',
    description: 'Sweeping views of the LA skyline and Hollywood sign. Night photography paradise with city lights stretching to the horizon.',
    latitude: 34.1184,
    longitude: -118.3004,
    founder_id: 'user-2',
    rank: 'iconic',
    difficulty: 'easy',
    tags: ['night', 'cityscape', 'sunset'],
    cover_photo_url: '',
    photo_count: 547,
    navigation_count: 412,
    best_time_start: '19:30',
    best_time_end: '22:00',
    gear_recommendation: '16-35mm f/2.8',
    created_at: '2024-02-10T08:00:00Z',
  },
  {
    id: '3',
    name: 'McWay Falls',
    description: 'A 80-foot waterfall cascading directly onto an untouched beach. One of the most dramatic coastal shots in California.',
    latitude: 36.1573,
    longitude: -121.6729,
    founder_id: 'user-3',
    rank: 'legendary',
    difficulty: 'easy',
    tags: ['waterfall', 'nature', 'sunrise'],
    cover_photo_url: '',
    photo_count: 891,
    navigation_count: 634,
    best_time_start: '06:00',
    best_time_end: '08:30',
    gear_recommendation: '70-200mm f/4',
    created_at: '2024-01-05T06:00:00Z',
  },
  {
    id: '4',
    name: 'Bow Bridge, Central Park',
    description: 'Classic cast iron bridge reflecting in the lake. Cherry blossoms in spring make this one of the most romantic spots in NYC.',
    latitude: 40.7756,
    longitude: -73.9712,
    founder_id: 'user-4',
    rank: 'popular',
    difficulty: 'easy',
    tags: ['architecture', 'nature', 'sunrise'],
    cover_photo_url: '',
    photo_count: 228,
    navigation_count: 156,
    best_time_start: '06:30',
    best_time_end: '08:00',
    gear_recommendation: '35mm f/1.8',
    created_at: '2024-03-20T07:00:00Z',
  },
  {
    id: '5',
    name: 'Antelope Canyon',
    description: 'Narrow slot canyon with otherworldly light beams in summer. The flowing sandstone walls glow orange and red at midday.',
    latitude: 36.8619,
    longitude: -111.3743,
    founder_id: 'user-5',
    rank: 'legendary',
    difficulty: 'permit_required',
    tags: ['architecture', 'nature'],
    cover_photo_url: '',
    photo_count: 1243,
    navigation_count: 867,
    best_time_start: '11:00',
    best_time_end: '13:30',
    gear_recommendation: '16-35mm f/4',
    created_at: '2023-11-10T09:00:00Z',
  },
  {
    id: '6',
    name: 'Rooftop 230 Fifth',
    description: 'NYC rooftop bar with Empire State Building right in your face. Foggy evenings create a magical atmosphere.',
    latitude: 40.7445,
    longitude: -73.9878,
    founder_id: 'user-6',
    rank: 'hidden_gem',
    difficulty: 'easy',
    tags: ['rooftop', 'night', 'cityscape'],
    cover_photo_url: '',
    photo_count: 87,
    navigation_count: 43,
    best_time_start: '20:00',
    best_time_end: '23:00',
    gear_recommendation: '50mm f/1.4',
    created_at: '2024-04-01T20:00:00Z',
  },
  {
    id: '7',
    name: 'Skull Rock, Joshua Tree',
    description: 'Unique granite boulders at sunrise with the desert sky turning pink and orange. Milky Way visible on clear nights.',
    latitude: 33.9944,
    longitude: -116.0392,
    founder_id: 'user-7',
    rank: 'popular',
    difficulty: 'easy',
    tags: ['sunrise', 'nature', 'night'],
    cover_photo_url: '',
    photo_count: 196,
    navigation_count: 112,
    best_time_start: '05:30',
    best_time_end: '07:30',
    gear_recommendation: '24mm f/1.4',
    created_at: '2024-02-28T05:00:00Z',
  },
  {
    id: '8',
    name: 'Golden Gate Vista Point',
    description: 'Classic north-side view of the Golden Gate Bridge. Fog rolling in from the bay makes this ethereal in the early morning.',
    latitude: 37.8324,
    longitude: -122.4795,
    founder_id: 'user-8',
    rank: 'iconic',
    difficulty: 'easy',
    tags: ['architecture', 'sunrise', 'nature'],
    cover_photo_url: '',
    photo_count: 743,
    navigation_count: 521,
    best_time_start: '06:00',
    best_time_end: '09:00',
    gear_recommendation: '70-200mm f/2.8',
    created_at: '2023-12-15T06:00:00Z',
  },
]
